<a href="https://colab.research.google.com/github/SachinSarin/Machine_Learning/blob/master/Single_Feature_Clasification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing

In [ ]:
temp=['green','green','green','green','red','red','red','red']

play=['Accept','Accept','Accept','Accept','Reject','Reject','Reject','Reject']

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
temp_encoded=le.fit_transform(temp)

In [ ]:
print(temp_encoded)

[0 0 0 0 1 1 1 1]


In [ ]:
label=le.fit_transform(play)

In [ ]:
print(label);

[0 0 0 0 1 1 1 1]


In [ ]:
model = GaussianNB()

In [ ]:
temp_encoded=temp_encoded.reshape(-1,1);
print(temp_encoded)

[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


In [ ]:
model.fit(temp_encoded,label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
predicted= model.predict([[0]])  

In [ ]:
if(predicted==1):
  print("Reject")
else:
  print("Accept")

Accept
